### ISSUE TITLE
s2i-minimal-notebook-py35:2.5.0 - not found.

### ISSUE THREAD

**Issue by cloudbustinguk** [jupyter-on-openshift/jupyterhub-quickstart#31]
Hi, 2.5.0 is not available on Quay:

https://quay.io/repository/jupyteronopenshift/s2i-minimal-notebook-py35?tab=tags

Unable to sync image for tag s2i-minimal-notebook:3.5. dockerimage.image.openshift.io "quay.io/jupyteronopenshift/s2i-minimal-notebook-py35:2.5.0" not found

Will it be made available soon?

cheers

**Comment by GrahamDumpleton** [comment]
Looks like when one of the Python packages in the `requirements.txt` file was updated, the newer version wasn't available for Python 3.5, only Python 3.6. Hadn't noticed there was an issue since I probably only checked that Python 3.6 had built. I'll have to work out a qualifier for the `requirements.txt` file which says to use older package version for Python 3.5.

**Comment by GrahamDumpleton** [comment]
Also should mention that the quickest solution to get around it until can fix it, is to edit the ``s2i-minimal-notebook`` image stream and modify the 3.5 tag so references 2.4.1 version of target image.

**Comment by cloudbustinguk** [comment]
Thanks Graham.

**Comment by GrahamDumpleton** [comment]
I think this should be fixed over in the jupyter-notebooks repository now. Loading the image stream file again should work.
